branches:
  only:
  - source
language: ruby
rvm:
  - 1.9.3
before_script:
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - rake setup_github_pages[$REPO_URL]
   # To reset the 'url' to the custom domain in '_config.yml'
  - git checkout -- _config.yml
script: 
  - rake generate
after_script:
  - rake deploy
env:
  global:
  - GH_REPO="futures/futures.github.com"
  - secure: "m1/GVowyxkWyjzwWHtVI41PJMH3vY0hdtPN9PPae7tKB3HmAscFz3M6f/PRF\ntI80A+c4OBvT0Ky1eAvLfjrGrNa8KdCMWci3O5BKqJhSzdzbF5OO00LKg5Av\nMf0wsOZuZLcsAvDw4kn99i0y7TN7kr9knQ3EPkpQX8PFs9J46wY="
